export const zoneDummyData = [
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 1,
        "companyName": "Tafjord Kraft AS",
        "companyZoneId": 1,
        "companyZoneName": "Bygg 2 i Holen",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 1,
                "companyName": "Tafjord Kraft AS",
                "companyZoneId": 1,
                "companyZoneName": "Bygg 2 i Holen",
                "sensorId": 1,
                "sensorNumber": "10690001",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "",
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 1,
        "companyName": "Tafjord Kraft AS",
        "companyZoneId": 2,
        "companyZoneName": "Bygg 3 i Holen",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 1,
                "companyName": "Tafjord Kraft AS",
                "companyZoneId": 2,
                "companyZoneName": "Bygg 3 i Holen",
                "sensorId": 2,
                "sensorNumber": "10572451",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "",
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 1,
        "companyName": "Tafjord Kraft AS",
        "companyZoneId": 3,
        "companyZoneName": "Bygg 4 i Holen",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 1,
                "companyName": "Tafjord Kraft AS",
                "companyZoneId": 3,
                "companyZoneName": "Bygg 4 i Holen",
                "sensorId": 3,
                "sensorNumber": "10731186",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "",
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 1,
        "companyName": "Tafjord Kraft AS",
        "companyZoneId": 63,
        "companyZoneName": "Øvrige målepunkt",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 1,
                "companyName": "Tafjord Kraft AS",
                "companyZoneId": 63,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 191,
                "sensorNumber": "88071108",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 1,
                "companyName": "Tafjord Kraft AS",
                "companyZoneId": 63,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 414,
                "sensorNumber": "39390210",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 1,
                "companyName": "Tafjord Kraft AS",
                "companyZoneId": 63,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 438,
                "sensorNumber": "10770451",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 1,
                "companyName": "Tafjord Kraft AS",
                "companyZoneId": 63,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 503,
                "sensorNumber": "44957033",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 1,
                "companyName": "Tafjord Kraft AS",
                "companyZoneId": 63,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 514,
                "sensorNumber": "39498152",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 3,
        "companyName": "Tafjord Kraftproduksjon AS",
        "companyZoneId": 4,
        "companyZoneName": "Tafjord Friluftsbad",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 4,
                "companyZoneName": "Tafjord Friluftsbad",
                "sensorId": 4,
                "sensorNumber": "88077339",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "",
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 3,
        "companyName": "Tafjord Kraftproduksjon AS",
        "companyZoneId": 5,
        "companyZoneName": "Tafjord T. K. verksted",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 5,
                "companyZoneName": "Tafjord T. K. verksted",
                "sensorId": 5,
                "sensorNumber": "88077407",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "",
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 3,
        "companyName": "Tafjord Kraftproduksjon AS",
        "companyZoneId": 65,
        "companyZoneName": "Øvrige målepunkt",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 129,
                "sensorNumber": "10757124",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 212,
                "sensorNumber": "88078275",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 244,
                "sensorNumber": "44976690",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 249,
                "sensorNumber": "88077353",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 255,
                "sensorNumber": "88077377",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 299,
                "sensorNumber": "44976737",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 333,
                "sensorNumber": "88077179",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 337,
                "sensorNumber": "88078329",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 346,
                "sensorNumber": "88078282",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 364,
                "sensorNumber": "88078145",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 405,
                "sensorNumber": "88078657",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 412,
                "sensorNumber": "88078770",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 432,
                "sensorNumber": "88078442",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 472,
                "sensorNumber": "88078312",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 488,
                "sensorNumber": "88077780",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 497,
                "sensorNumber": "39414756",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 534,
                "sensorNumber": "39414985",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 543,
                "sensorNumber": "39414992",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 550,
                "sensorNumber": "10757131",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 10515,
                "sensorNumber": "10772202",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 65,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 98174,
                "sensorNumber": "88078305",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "TAFJORD BUSTAD FLØHUSET",
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 3,
        "companyName": "Tafjord Kraftproduksjon AS",
        "companyZoneId": 39666,
        "companyZoneName": "Historiske målepunkt",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 39666,
                "companyZoneName": "Historiske målepunkt",
                "sensorId": 102281,
                "sensorNumber": "88078152",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 39666,
                "companyZoneName": "Historiske målepunkt",
                "sensorId": 102282,
                "sensorNumber": "88078336",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 3,
                "companyName": "Tafjord Kraftproduksjon AS",
                "companyZoneId": 39666,
                "companyZoneName": "Historiske målepunkt",
                "sensorId": 102283,
                "sensorNumber": "88078367",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 4,
        "companyName": "Tafjord Connect AS",
        "companyZoneId": 66,
        "companyZoneName": "Øvrige målepunkt",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 121,
                "sensorNumber": "10735566",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 130,
                "sensorNumber": "64086331",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 141,
                "sensorNumber": "10961675",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 142,
                "sensorNumber": "10736969",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 148,
                "sensorNumber": "10767413",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 157,
                "sensorNumber": "10735269",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 165,
                "sensorNumber": "10735054",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 168,
                "sensorNumber": "10773735",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 188,
                "sensorNumber": "10735023",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 190,
                "sensorNumber": "10778778",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 195,
                "sensorNumber": "10735580",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 197,
                "sensorNumber": "10735573",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 200,
                "sensorNumber": "10772448",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 204,
                "sensorNumber": "39421396",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 227,
                "sensorNumber": "10735047",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 246,
                "sensorNumber": "39427336",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 262,
                "sensorNumber": "10758305",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 271,
                "sensorNumber": "10733203",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 272,
                "sensorNumber": "10758299",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 276,
                "sensorNumber": "64081374",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 283,
                "sensorNumber": "64094817",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 284,
                "sensorNumber": "10735016",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 288,
                "sensorNumber": "64092271",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 292,
                "sensorNumber": "10738949",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 298,
                "sensorNumber": "10769080",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 308,
                "sensorNumber": "10781891",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 311,
                "sensorNumber": "64099614",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 317,
                "sensorNumber": "10737522",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 320,
                "sensorNumber": "10739274",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 325,
                "sensorNumber": "64094800",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 356,
                "sensorNumber": "64102338",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 381,
                "sensorNumber": "10739465",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 387,
                "sensorNumber": "64097993",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 408,
                "sensorNumber": "10786148",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 419,
                "sensorNumber": "64094794",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 433,
                "sensorNumber": "64101010",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 441,
                "sensorNumber": "10737898",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 442,
                "sensorNumber": "10739748",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 450,
                "sensorNumber": "10735467",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 452,
                "sensorNumber": "64094831",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 458,
                "sensorNumber": "10735030",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 459,
                "sensorNumber": "10952901",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 470,
                "sensorNumber": "64097979",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 487,
                "sensorNumber": "10735542",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 493,
                "sensorNumber": "39421259",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 513,
                "sensorNumber": "10737706",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 515,
                "sensorNumber": "10739311",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 518,
                "sensorNumber": "10739472",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 527,
                "sensorNumber": "10738956",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 530,
                "sensorNumber": "39421037",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 549,
                "sensorNumber": "10735559",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 85554,
                "sensorNumber": "39399787",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "Nodehus Lied",
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 90570,
                "sensorNumber": "10984674",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "Annen næringsvirksomhet",
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 90882,
                "sensorNumber": "64105995",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 91503,
                "sensorNumber": "11000779",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "Driftsbygninger",
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 91652,
                "sensorNumber": "64108309",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "Nodestasjon",
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 92332,
                "sensorNumber": "64108439",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "Fiber/nodestasjon",
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 96664,
                "sensorNumber": "64108477",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "Fiber/nodestasjon",
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 4,
                "companyName": "Tafjord Connect AS",
                "companyZoneId": 66,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 97624,
                "sensorNumber": "10998718",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "Driftsbygninger",
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 5,
        "companyName": "Tafjord Kraftvarme AS",
        "companyZoneId": 6,
        "companyZoneName": "Åsehaugen 5",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 6,
                "companyZoneName": "Åsehaugen 5",
                "sensorId": 6,
                "sensorNumber": "10562841",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "",
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 5,
        "companyName": "Tafjord Kraftvarme AS",
        "companyZoneId": 7,
        "companyZoneName": "Borgundfjordvegen 0",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 7,
                "companyZoneName": "Borgundfjordvegen 0",
                "sensorId": 7,
                "sensorNumber": "10742052",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "",
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 5,
        "companyName": "Tafjord Kraftvarme AS",
        "companyZoneId": 8,
        "companyZoneName": "Brevika Industriveg 1A",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 8,
                "companyZoneName": "Brevika Industriveg 1A",
                "sensorId": 8,
                "sensorNumber": "10568867",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "",
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 5,
        "companyName": "Tafjord Kraftvarme AS",
        "companyZoneId": 9,
        "companyZoneName": "Klaus Nilsens gate 6",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 9,
                "companyZoneName": "Klaus Nilsens gate 6",
                "sensorId": 9,
                "sensorNumber": "10416472",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "",
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 9,
                "companyZoneName": "Klaus Nilsens gate 6",
                "sensorId": 10,
                "sensorNumber": "10941103",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "",
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 9,
                "companyZoneName": "Klaus Nilsens gate 6",
                "sensorId": 11,
                "sensorNumber": "10941097",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "",
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 5,
        "companyName": "Tafjord Kraftvarme AS",
        "companyZoneId": 10,
        "companyZoneName": "Sjømannsvegen 14",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 10,
                "companyZoneName": "Sjømannsvegen 14",
                "sensorId": 12,
                "sensorNumber": "10696065",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "",
                "zoneDescription": null
            }
        ]
    },
    {
        "userId": 322,
        "userName": "olavval@stud.ntnu.no",
        "companyId": 5,
        "companyName": "Tafjord Kraftvarme AS",
        "companyZoneId": 67,
        "companyZoneName": "Øvrige målepunkt",
        "userCompanyZoneId": 0,
        "accessTypeName": "inherited",
        "sensors": [
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 67,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 189,
                "sensorNumber": "10761053",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 67,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 254,
                "sensorNumber": "10688978",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 67,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 282,
                "sensorNumber": "10568881",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 67,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 322,
                "sensorNumber": "10774787",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 67,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 469,
                "sensorNumber": "10785486",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 67,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 526,
                "sensorNumber": "10666976",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 67,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 538,
                "sensorNumber": "10942827",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": null,
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 67,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 88721,
                "sensorNumber": "10979410",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "Elkjele 1-2",
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 67,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 94854,
                "sensorNumber": "10986975",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "Vekslerstasjon Åsegardane",
                "zoneDescription": null
            },
            {
                "userId": 322,
                "userName": "olavval@stud.ntnu.no",
                "companyId": 5,
                "companyName": "Tafjord Kraftvarme AS",
                "companyZoneId": 67,
                "companyZoneName": "Øvrige målepunkt",
                "sensorId": 96807,
                "sensorNumber": "10979427",
                "sensorTypeId": 1,
                "sensorTypeName": "El",
                "description": "Elkjeler 3-4",
                "zoneDescription": null
            }
        ]
    }
]